services:
  # 1. MySQL
  db-mysql:
    container_name: sandbox_Mysql
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --lower_case_table_names=1
    volumes:
      - C:/Data/:/var/lib/mysql

  # 2. Redis
  redis:
    container_name: redis-ssafy
    image: redis:alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # 3. Spring Boot
  sandbox:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
#      - db-mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      # Database Configuration
      DATABASE_URL: jdbc:mysql://db-mysql:3306/${MYSQL_DATABASE}
      DATABASE_USER_NAME: ${MYSQL_ROOT_USER}
      DATABASE_USER_PASSWORD: ${MYSQL_PASSWORD}

#      DATABASE_URL: jdbc:mysql://sand.ctec4gw8ivv9.us-east-1.rds.amazonaws.com:3306/${MYSQL_DATABASE}
#      DATABASE_USER_NAME: ${MYSQL_ROOT_USER}
#      DATABASE_USER_PASSWORD: ${MYSQL_PASSWORD}

      # Redis Configuration
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      # Mail Configuration
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_NAME: dkanfjgwls@gmail.com
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      # OAuth Configuration
      KAKAO_RESTAPI_KEY: ${KAKAO_RESTAPI_KEY}
      CLIENT_ID: ${CLIENT_ID}
      REDIRECT_URI: ${REDIRECT_URI}

      # Kakao Auth URLs
      KAUTH_USER_URL_HOST: ${KAUTH_USER_URL_HOST}
      KAUTH_TOKEN_URL_HOST: ${KAUTH_TOKEN_URL_HOST}
      KAUTH_TOKEN_URL_PATH: ${KAUTH_TOKEN_URL_PATH}
      KAUTH_USER_URL_PATH: ${KAUTH_USER_URL_PATH}

      # Application Configuration
      REQUEST_SIZE: ${REQUEST_SIZE}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}

volumes:
  db-data:
  redis-data:
